version: "3.8"

services:
  react-base:
    container_name: react-base
    build:
      dockerfile: Dockerfile
      context: .
    stdin_open: true
    ports:
      - "4000:4000"
    volumes:
      - "${PWD}:/app"
      - "/app/node_modules"
