version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Run build
          command: npm run build

workflows:
  build_and_test:
    jobs:
      - build_and_test
