name: CI
on: [push]
jobs:
  build:
    name: Lint, test and build on Node 18.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci --maxWorkers=2

      - name: Build
        run: yarn build
